FROM node:24.10.0-alpine AS core
WORKDIR /app

RUN npm install -g prisma

COPY ./prisma ./prisma

ENV CONNET_TIMEOUT=60

CMD ["sh", "-c", "env DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEMA}\\&connect_timeout=${CONNET_TIMEOUT:-10} prisma migrate deploy --schema ./prisma"]